# Generated by Django 2.0.7 on 2018-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180719_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
    ]
