# Generated by Django 2.0.7 on 2018-09-15 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180911_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Не уверен'), (1, 'Мужик'), (2, 'Девушка'), (3, 'Другой')], default=0)),
                ('about', models.TextField(blank=True, max_length=512, verbose_name='О себе')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
