# Generated by Django 2.0.7 on 2018-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='G+ автарка'),
        ),
    ]
