# Generated by Django 2.0.7 on 2018-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='g_plus',
            field=models.URLField(blank=True, null=True, verbose_name='G+ link'),
        ),
    ]
