# Generated by Django 2.0.7 on 2018-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_g_plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='g_plus',
        ),
        migrations.AddField(
            model_name='accountextra',
            name='g_plus',
            field=models.URLField(blank=True, null=True, verbose_name='G+ link'),
        ),
        migrations.AlterField(
            model_name='accountextra',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не Скажу'), (1, 'Мужик'), (2, 'Девушка')], default=0),
        ),
    ]
